// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiaz3b9hJJlXzD5kpE7dAJBC5gmzhv_3w',
    appId: '1:366296665013:web:b47362835e331eecda27fc',
    messagingSenderId: '366296665013',
    projectId: 'vegetable-f8839',
    authDomain: 'vegetable-f8839.firebaseapp.com',
    storageBucket: 'vegetable-f8839.firebasestorage.app',
    measurementId: 'G-XES3851JFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJHdAok9_YHCVYqKRyT1g9g1KK3ycBB3g',
    appId: '1:366296665013:android:fedf6cd5d8203e01da27fc',
    messagingSenderId: '366296665013',
    projectId: 'vegetable-f8839',
    storageBucket: 'vegetable-f8839.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiaz3b9hJJlXzD5kpE7dAJBC5gmzhv_3w',
    appId: '1:366296665013:web:7ec0e6c4937cfa2eda27fc',
    messagingSenderId: '366296665013',
    projectId: 'vegetable-f8839',
    authDomain: 'vegetable-f8839.firebaseapp.com',
    storageBucket: 'vegetable-f8839.firebasestorage.app',
    measurementId: 'G-463ZQMQ7R0',
  );
}
